### ISSUE TITLE
Fatal error in detailview and upgrade wizard doesn't execute anything.

### ISSUE THREAD

**Issue by sinasita** [georgringer/news-documentation#12]
When i try to open the detailview of a newsentry, following error comes up:

PHP Catchable Fatal Error: Argument 1 passed to GeorgRinger\News\ViewHelpers\LinkViewHelper::render() must be an instance of GeorgRinger\News\Domain\Model\News, null given in html/typo3conf/ext/news/Classes/ViewHelpers/LinkViewHelper.php line 87

I'm using records.contentElementRelation = 1 and i already tried to run the upgrad wizard, which prevents to have been successful, but it executes nothing and all the entries are still shown as if they wouldn't have been migrated

**Comment by georgringer** [comment]
This repo is only for documentation, please use Forge! 
Am 19.05.2015 16:58 schrieb stefanie axinger <notifications@github.com>:When i try to open the detailview of a newsentry, following error comes up:

PHP Catchable Fatal Error: Argument 1 passed to GeorgRinger\News\ViewHelpers\LinkViewHelper::render() must be an instance of GeorgRinger\News\Domain\Model\News, null given in html/typo3conf/ext/news/Classes/ViewHelpers/LinkViewHelper.php line 87

I'm using records.contentElementRelation = 1 and i already tried to run the upgrad wizard, which prevents to have been successful, but it executes nothing and all the entries are still shown as if they wouldn't have been migrated

**Comment by sinasita** [comment]
ok, i moved the upgrade wizard issue to forge:
https://forge.typo3.org/issues/67064
