### ISSUE TITLE
Load a news list module inside a fluid template from another ext ?

### ISSUE THREAD

**Issue by kaolol** [georgringer/news-documentation#16]
HI Georg !
Is it possible to load a news list module inside a fluid template from another ext ?
I would like to display news from a feuser on this profile page in FE ( provided by EXT:femanager )
Any tips on how to achieve that ?

**Comment by georgringer** [comment]
This is just a repository for the documentation, support at Forge please

**Comment by kaolol** [comment]
Thank you for you reply ! 
Posted on forge 
https://forge.typo3.org/issues/69413

Allt he best,
Laurent
