### ISSUE TITLE
Not possible to switch Categories in 4.0

### ISSUE THREAD

**Issue by eeels** [georgringer/news-documentation#20]
hi,

plugin.tx_news.settings.disableOverrideDemand has no action in Typo3 7.6 / News 4.0.
There's no Filter with the category menu.
Thats the url ?tx_news_pi1[overwriteDemand][categories]=1

best regards
micha

**Comment by georgringer** [comment]
Sorry for the late response. this repository is for the documentation only. If the issue is still valid, please reopen it at https://forge.typo3.org/projects/extension-news/issues or https://github.com/TYPO3-extensions/news and add a bit more information!
