### ISSUE TITLE
TX_news Media link is not generating properly

### ISSUE THREAD

**Issue by Nageshwar** [georgringer/news-documentation#26]
Hello Everyone,
I am getting network error when i want to insert media element using typo3 tx_news 4.0.0 extension.
This error is due to real url which is getting added to the media url and which results video not found.

I am also attaching a snapshot which will give you the exact idea of error.
![bug news 4 0 0](https://cloud.githubusercontent.com/assets/3288042/15700245/73ff67ac-27f0-11e6-91de-16ba292bab7e.png)

Please suggest me some way for that

Thanking you 

Nageshwar Jha

**Comment by martinhummer** [comment]
hi nageshwar,
the right place to ask your question would be the ext-news channel on typo3 slack.

**Comment by Nageshwar** [comment]
Thanks
